In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#exercise1
array = np.array([0, 1, 2, 3, 4, 5,6 , 7, 8, 9])
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#exercise 1bis
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#exercise 2
float_array = np.array([3.14, 2.17, 0, 1, 2])

integer_array = float_array.astype(int) #convert to intger, 3.6 will become 3
integer_array

array([3, 2, 0, 1, 2])

In [5]:
#exercise 3
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#exercise 4
random_array = np.random.rand(4, 5)

random_array

array([[0.32068566, 0.58809516, 0.21542551, 0.44327591, 0.81484909],
       [0.84703181, 0.18358384, 0.15664584, 0.38097572, 0.42893321],
       [0.99219502, 0.03273741, 0.4229998 , 0.28116314, 0.58868977],
       [0.36862618, 0.59793421, 0.23683709, 0.89280521, 0.41209352]])

In [11]:
#exercise 5

array = np.array([[21,22,23,22,22],
                  [20,21,22,23,24],
                  [21,22,23,22,22]])

second_row = array[1]
second_row

array([20, 21, 22, 23, 24])

In [13]:
#exercise 6
array = np.arange(10)

reverse_array = array[::-1]

reverse_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [14]:
#exercise 7
matrix = np.diag(np.ones(4))

matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
#exercise 8
array = np.arange(10)

sum_array = np.sum(array)

sum_array

np.int64(45)

In [17]:
average_array = np.mean(array)
average_array

np.float64(4.5)

In [18]:
#exercise 9
array = np.arange(1, 21)
matrix = array.reshape(4, 5)

matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
#Exercise 10
array = np.arange(10)
numbers_array = array[1::2]



numbers_array

array([1, 3, 5, 7, 9])